# See http://docs.spring.io/spring-boot/docs/current/reference/html/common-application-properties.html
spring:
  main.show-banner: false
#  spring.mvc.throw-exception-if-no-handler-found: true
#  resources.add-mappings: false